apiVersion: v1
kind: Namespace
metadata:
  name: openshift-keda
  labels:
    app.kubernetes.io/part-of: datamesh
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-keda
  namespace: openshift-keda
spec:
  targetNamespaces:
    - openshift-keda
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-custom-metrics-autoscaler-operator
  namespace: openshift-keda
  labels:
    app.kubernetes.io/part-of: datamesh
spec:
  name: openshift-custom-metrics-autoscaler-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  channel: stable
  startingCSV: custom-metrics-autoscaler.v2.19.0-4
  installPlanApproval: Manual
