apiVersion: v1
kind: Namespace
metadata:
  name: openshift-gitops-operator
  labels:
    app.kubernetes.io/part-of: datamesh
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-gitops-operator
  namespace: openshift-gitops-operator
spec:
  upgradeStrategy: Default
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-gitops-operator
  namespace: openshift-gitops-operator
  labels:
    app.kubernetes.io/part-of: datamesh
spec:
  name: openshift-gitops-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  channel: gitops-1.22
  startingCSV: openshift-gitops-operator.v1.22.1
  installPlanApproval: Manual
