package com.patterncatalyst.datamesh.order;

import java.time.Duration;

import capstone.inventory.v1.Inventory.CheckStockRequest;
import capstone.inventory.v1.Inventory.CheckStockResponse;
import capstone.inventory.v1.InventoryService;

import io.quarkus.grpc.GrpcClient;
import jakarta.enterprise.context.ApplicationScoped;

/**
 * gRPC client wrapper for the order flow's one synchronous cross-service
 * dependency: before persisting an order, ask inventory-service whether the
 * requested SKU/quantity is available. Mirrors
 * {@code app/inventory_client.py::check_stock} in the Python reference
 * architecture (CAP-012 -- gRPC fits a tight request/response between two
 * internal services).
 *
 * <p>{@code InventoryService} is the Mutiny service interface generated by
 * quarkus-grpc from {@code capstone/inventory/v1/inventory.proto}, which is
 * scanned out of the {@code contracts} dependency jar -- see
 * {@code quarkus.generate-code.grpc.scan-for-proto} in
 * {@code application.properties}. It is not regenerated or hand-written
 * here.
 *
 * <p>A failed/timed-out RPC (e.g. {@code io.grpc.StatusRuntimeException})
 * propagates to the caller uncaught -- {@link OrderResource} fails closed
 * (503) rather than place an order it couldn't validate, exactly like the
 * Python {@code InventoryUnreachable} case.
 */
@ApplicationScoped
public class InventoryClient {

    private static final Duration CALL_TIMEOUT = Duration.ofSeconds(3);

    @GrpcClient("inventory")
    InventoryService inventoryService;

    /**
     * @return the upstream {@code CheckStockResponse} (available +
     *         quantityOnHand). Blocks the calling (worker) thread up to
     *         {@link #CALL_TIMEOUT} waiting for the reactive gRPC call.
     */
    public CheckStockResponse checkStock(String sku, int quantity) {
        CheckStockRequest request = CheckStockRequest.newBuilder()
                .setSku(sku)
                .setQuantity(quantity)
                .build();
        return inventoryService.checkStock(request)
                .await().atMost(CALL_TIMEOUT);
    }
}
