apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: datamesh

resources:
  - config.yaml
  - order-service.yaml
  - inventory-service.yaml
  - notification-service.yaml
  - graphql-gateway.yaml
